### ISSUE TITLE
Issues with the properties argument of the repository resource

### ISSUE THREAD

**Issue by VictorGFM** [cyralinc/terraform-provider-cyral#268]
1) The `properties` argument of the `cyral_repository` resource is generating a non-empty plan at every `terraform apply` when it is specified as an empty block. One way to fix that would be to validate if the `properties` block is empty, and if it is we should require that at least one property is specified (`AtLeastOneOf` can be used for that).

Config:
```terraform
resource "cyral_repository" "pg_repo" {
  name = "pgrepo"
  type = "postgresql"
  host = "some-host"
  port = 5432
  properties {}
}
```

Result:
```terraform
Terraform will perform the following actions:

  # cyral_repository.pg_repo will be updated in-place
  ~ resource "cyral_repository" "pg_repo" {
        id     = "2D5gZ7EsdCwmutxcO9VNSUrXcpX"
        name   = "pgrepo"
        # (4 unchanged attributes hidden)

      + properties {
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

2) Also, there's another issue regarding the `properties` argument on the version `2.7.1` of the provider. If a data repository object has a non-empty `properties` field, but it does not match the following condition:
```go
data.Properties != nil && data.Properties.MongoDBServerType == mongodbReplicaSetServerType
```
An error occurs since the provider will try to set an empty map to the `properties` argument (which is a `TypeSet`).
This issue was already fixed in version `2.8.0`, but we should create a patch to fix it for `2.7.x`.

Repo object example:
```json
{
    "repo": {
        "name": "pgrepo",
        "type": "postgresql",
        "repoHost": "some-host",
        "repoPort": 5432,
        "connParams": {
            "connDraining": {
                "auto": false,
                "waitTime": 0
            }
        },
        "labels": [],
        "properties": {
            "test": "test"
        }
    },
    "sidecars": null
}
```

Error logs:
```
panic: set item just set doesn't exist

goroutine 103 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0xc00068fe30, {0xc00090ef50, 0x1, 0xc00007a3c0}, {0x17a37e0, 0xc00068fec0}, 0xc000420dc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/field_writer_map.go:327 +0x972
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0xc00068fe30, {0xc00090ef50, 0x1, 0x1}, {0x17a37e0, 0xc00068fec0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/field_writer_map.go:107 +0x14c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0xc00068fe30, {0xc00090ef50, 0x1, 0x1}, {0x17a37e0, 0xc00068fec0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/field_writer_map.go:89 +0x3f9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc0004ad200, {0x18b811e, 0xa}, {0x17a37e0, 0xc00068fec0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource_data.go:227 +0x21c
github.com/cyralinc/terraform-provider-cyral/cyral.(*RepoData).WriteToSchema(0xc0000ca540, 0xc0001440a0)
	github.com/cyralinc/terraform-provider-cyral/cyral/resource_cyral_repository.go:64 +0x365
github.com/cyralinc/terraform-provider-cyral/cyral.resourceRepositoryRead({0x1a72e60, 0xc00099e150}, 0xc0004ad200, {0x17d2ae0, 0xc0002f51c0})
	github.com/cyralinc/terraform-provider-cyral/cyral/resource_cyral_repository.go:236 +0x6ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00041c9a0, {0x1a72e60, 0xc00099e150}, 0xd, {0x17d2ae0, 0xc0002f51c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00041c9a0, {0x1a72e60, 0xc00099e150}, 0xc0004cec30, {0x17d2ae0, 0xc0002f51c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c018, {0x1a72db8, 0xc0004cc540}, 0xc0004cc5c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00042a000, {0x1a72e60, 0xc000693b90}, 0xc00080cc60)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x188a300, 0xc00042a000}, {0x1a72e60, 0xc000693b90}, 0xc00080cc00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c0700, {0x1a80468, 0xc0004f49c0}, 0xc0009958c0, 0xc00007aab0, 0x1f819b0, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0000c0700, {0x1a80468, 0xc0004f49c0}, 0xc0009958c0, 0x0)
	google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.0/server.go:920 +0x294
```

**Comment by Yowgf** [comment]
In the process of fixing these issues, I actually found another one:

Initial config:

```
resource "cyral_repository" "mongodb" {
    host = "localhost"
    port = 27017
    type = "mongodb"
    name = "mongodb-1"
    properties {
      mongodb_replica_set {
        max_nodes = 1
        replica_set_id = "some-replica-set-id"
      }
    }
}
```

Run `terraform apply`. Then, remove `mongodb_replica_set` from config:

```
resource "cyral_repository" "sqlserver1" {
    host = "localhost"
    port = 1433
    type = "mongodb"
    name = "aholmquist-mongodb-1"
    properties {
    }
}
```

The plan is empty.

FYI @VictorGFM

**Comment by Yowgf** [comment]
> In the process of fixing these issues, I actually found another one

Actually, it doesn't seem to be possible to fix this in any way I can imagine... I am not sure if we could try to manipulate the `StateFunc` in the argument's schema, but essentially when we read `*schema.Resource` data in the CRUD functions in the resource, we don't see any difference in the `properties` field, which I found really weird, but yeah...

CC @VictorGFM
